version: 0.0.0-build_{build}

environment:
  matrix:

  - job_name: win64
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: linux_x64
    appveyor_build_worker_image: Ubuntu1804

  - job_name: macOS_x64
    appveyor_build_worker_image: macos

configuration:
  - Release

for:

# win64

  -
    matrix:
      only:
        - job_name: win64
    cache:
    - Cmpl-2-0-win.zip

    install:
      - set QTDIR=C:\Qt\5.15\msvc2019_64
      - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.15\msvc2019_64\bin
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    build_script:
      - if not exist Cmpl-2-0-1-win.zip appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-1-win.zip
      - 7z x Cmpl-2-0-1-win.zip
      - cd Cmpl-2-0-1-win
      - attrib -r -s -h /S /D
      - cd ..
      - ps: $env:VERSION_STRING = $(git describe --always --dirty=dev)
      - echo .pragma library > src\qml\version.js
      - echo var VERSION_STRING = "%VERSION_STRING%"; >> src\qml\version.js
      - qmake OverlayPal.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
      - nmake
    after_build:
      - mkdir OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%
      - cd OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%
      - copy ..\LICENSE .\
      - copy ..\release\OverlayPal.exe
      - xcopy ..\release\nespalettes nespalettes\
      - copy ..\release\*.cmpl .\
      - xcopy /s /i ..\release\Cmpl Cmpl\
      - windeployqt.exe --qmldir ..\src\qml OverlayPal.exe
      - cd ..
      - ps: 7z a OverlayPal-$env:VERSION_STRING-win64-$env:CONFIGURATION.zip OverlayPal-$env:VERSION_STRING-win64-$env:CONFIGURATION
      - dir
      - appveyor PushArtifact OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%.zip

# linux_x64

  -
    matrix:
      only:
        - job_name: linux_x64
    cache:
    - Cmpl-2-0-linux64.tar.gz
    - linuxdeployqt-continuous-x86_64.AppImage

    install:
      - PATH=$HOME/Qt/5.15/gcc_64/bin:$PATH
      - sh: sudo apt update
      - sh: sudo apt install -y libgl1-mesa-dev
    build_script:
      - if ! [ -f Cmpl-2-0-1-linux64.tar.gz ]; then appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-1-linux64.tar.gz; fi
      - if ! [ -f linuxdeployqt-continuous-x86_64.AppImage ]; then appveyor DownloadFile https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage; fi
      - chmod ugo+x linuxdeployqt-continuous-x86_64.AppImage
      - tar -xvf Cmpl-2-0-1-linux64.tar.gz
      - git clone https://github.com/MikeSteglich/Cmpl2.git
      - cd Cmpl2
      - git checkout 7cc8699edc948be77af4776a359955cc715a31a8
      - make
      - cd ..
      - cp Cmpl2/bin/cmpl Cmpl-2-0-1-linux64/bin/
      - cp Cmpl2/bin/.modules Cmpl-2-0-1-linux64/bin/
      - VERSION_STRING=$(git describe --always --dirty=dev)
      - echo ".pragma library" > src/qml/version.js
      - echo "var VERSION_STRING = \"${VERSION_STRING}\";" >> src/qml/version.js
      - qmake OverlayPal.pro "CONFIG+=qtquickcompiler"
      - make
    after_build:
      - mkdir OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - cp -r AppDir OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}/
      - cd OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - cp ../LICENSE ./AppDir/
      - mkdir -p ./AppDir/usr/bin
      - cp ../OverlayPal ./AppDir/usr/bin/
      - cp -r ../nespalettes ./AppDir/usr/bin/
      - cp ../*.cmpl ./AppDir/usr/bin/
      - cp -r ../Cmpl ./AppDir/usr/bin/
      - ../linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/OverlayPal.desktop -qmldir=../src/qml -ignore-glob=usr/bin/Cmpl/**
      - cd ..
      - tar -czvf OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}.tar.gz OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - appveyor PushArtifact OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}.tar.gz

# macOS (x64)

  -
    matrix:
      only:
        - job_name: macOS_x64
    cache:
    - Cmpl-2-0-macOs-Intel.zip

    install:
      - PATH=$HOME/Qt/5.15.2/clang_64/bin:$PATH
    build_script:
      - VERSION_STRING=$(git describe --always --dirty=dev)
      - mkdir OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - if ! [ -f Cmpl-2-0-1-macOs-Intel.zip ]; then appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-1-macOs-Intel.zip; fi
      - unzip Cmpl-2-0-1-macOs-Intel.zip
      - echo ".pragma library" > src/qml/version.js
      - echo "var VERSION_STRING = \"${VERSION_STRING}\";" >> src/qml/version.js
      - qmake OverlayPal.pro "CONFIG+=qtquickcompiler"
      - make
    after_build:
      - cd OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - cp ../LICENSE ./
      - cp -r ../OverlayPal.app ./
      - macdeployqt OverlayPal.app -qmldir=../src/qml
      - cd ..
      - tar -czvf OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}.tar.gz OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - appveyor PushArtifact OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}.tar.gz

