version: 0.0.0-build_{build}

environment:
  matrix:

#  - job_name: win64
#    appveyor_build_worker_image: Visual Studio 2019

  - job_name: linux_x64
    appveyor_build_worker_image: Ubuntu1804

  - job_name: macOS_x64
    appveyor_build_worker_image: macos

configuration:
  - Release

for:

# win64

  -
    matrix:
      only:
        - job_name: win64
    cache:
    - Cmpl-2-0-win.zip

    install:
      - set QTDIR=C:\Qt\5.15\msvc2019_64
      - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.15\msvc2019_64\bin
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    build_script:
      - ps: $env:VERSION_STRING = $(git describe --always --dirty=dev)
      - echo .pragma library > src\qml\version.js
      - echo var VERSION_STRING = "%VERSION_STRING%"; >> src\qml\version.js
      - qmake OverlayPal.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
      - nmake
    after_build:
      - if not exist Cmpl-2-0-win.zip appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-win.zip
      - mkdir OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%
      - cd OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%
      - copy ..\LICENSE .\
      - copy ..\release\OverlayPal.exe
      - xcopy ..\nespalettes nespalettes\
      - copy ..\src\cmpl\*.cmpl .\
      - 7z x ..\Cmpl-2-0-win.zip
      - rename Cmpl-2-0-win Cmpl
      - windeployqt.exe --qmldir ..\src\qml OverlayPal.exe
      - cd ..
      - ps: 7z a OverlayPal-$env:VERSION_STRING-win64-$env:CONFIGURATION.zip OverlayPal-$env:VERSION_STRING-win64-$env:CONFIGURATION
      - dir
      - appveyor PushArtifact OverlayPal-%VERSION_STRING%-win64-%CONFIGURATION%.zip

# linux_x64

  -
    matrix:
      only:
        - job_name: linux_x64
    cache:
    - Cmpl-2-0-linux64.tar.gz

    install:
      - PATH=$HOME/Qt/5.15/gcc_64/bin:$PATH
      - sh: sudo apt update
      - sh: sudo apt install -y libgl1-mesa-dev
    build_script:
      - VERSION_STRING=$(git describe --always --dirty=dev)
      - echo ".pragma library" > src/qml/version.js
      - echo "var VERSION_STRING = \"${VERSION_STRING}\";" >> src/qml/version.js
      - qmake OverlayPal.pro "CONFIG+=qtquickcompiler"
      - make
    after_build:
      - if ! [ -f Cmpl-2-0-linux64.tar.gz ]; then appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-linux64.tar.gz; fi
      - mkdir OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - cd OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - cp ../LICENSE ./
      - cp ../OverlayPal ./
      - cp -r ../nespalettes ./
      - cp ../src/cmpl/*.cmpl ./
      - tar -xvf ../Cmpl-2-0-linux64.tar.gz
      - mv Cmpl-2-0-linux64 Cmpl
      - cd ..
      - tar -czvf OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}.tar.gz OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}
      - appveyor PushArtifact OverlayPal-${VERSION_STRING}-linux_x64-${CONFIGURATION}.tar.gz

# macOS (x64)

  -
    matrix:
      only:
        - job_name: macOS_x64
    cache:
    - Cmpl-2-0-macOs-Intel.zip

    install:
      - PATH=$HOME/Qt/5.15.2/clang_64/bin:$PATH
#      - sh: sudo apt update
#      - sh: sudo apt install -y libgl1-mesa-dev
    build_script:
      - VERSION_STRING=$(git describe --always --dirty=dev)
      - echo ".pragma library" > src/qml/version.js
      - echo "var VERSION_STRING = \"${VERSION_STRING}\";" >> src/qml/version.js
      - echo $PATH
      - ls -la $HOME/Qt/5.15.2/clang_64/bin/
      - qmake OverlayPal.pro "CONFIG+=qtquickcompiler"
      - make
    after_build:
      - if ! [ -f http://www.coliop.org/_download/Cmpl-2-0-macOs-Intel.zip ]; then appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-macOs-Intel.zip; fi
      - mkdir OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - cd OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - cp ../LICENSE ./
      - ls -la ./
      - ls -la ../
      - cp -r ../OverlayPal.app ./
#      - cp -r ../nespalettes ./OverlayPal.app/Contents/MacOS/
#      - cp ../src/cmpl/*.cmpl ./OverlayPal.app/Contents/MacOS/
      - unzip ../Cmpl-2-0-macOs-Intel.zip
      - cp -r Cmpl-2-0-macOs-Intel/Cmpl2/Coliop.app/Contents/MacOS ./OverlayPal.app/Contents/MacOS/
      - mv ./OverlayPal.app/Contents/MacOS/MacOS ./OverlayPal.app/Contents/MacOS/Cmpl
      - rm -rf Cmpl-2-0-macOs-Intel
      - macdeployqt OverlayPal.app -dmg -qmldir=../src/qml
      - cd ..
      - tar -czvf OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}.tar.gz OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}
      - appveyor PushArtifact OverlayPal-${VERSION_STRING}-macOS_x64-${CONFIGURATION}.tar.gz

