version: 0.0.0-build_{build}

environment:
  matrix:

  - job_name: win64
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: linux_x64
    appveyor_build_worker_image: Ubuntu1804

configuration:
  - Release

for:

# win64

  -
    matrix:
      only:
        - job_name: win64

    install:
      - set QTDIR=C:\Qt\5.15\msvc2019_64
      - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.15\msvc2019_64\bin
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    build_script:
      - qmake OverlayPal.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
      - nmake
    after_build:
      - mkdir OverlayPal-dev-win64-%CONFIGURATION%
      - cd OverlayPal-dev-win64-%CONFIGURATION%
      - copy ..\LICENSE .\
      - copy ..\release\OverlayPal.exe
      - xcopy ..\nespalettes nespalettes\
      - copy ..\src\cmpl\*.cmpl .\
      - appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-win.zip
      - 7z x Cmpl-2-0-win.zip
      - del Cmpl-2-0-win.zip
      - rename Cmpl-2-0-win Cmpl
      - windeployqt.exe --qmldir ..\src\qml OverlayPal.exe
      - cd ..
      - 7z a OverlayPal-dev-win64-%CONFIGURATION%.zip OverlayPal-dev-win64-%CONFIGURATION%
      - appveyor PushArtifact OverlayPal-dev-win64-%CONFIGURATION%.zip

# linux_x64

  -
    matrix:
      only:
        - job_name: linux_x64

    install:
      - PATH=$HOME/Qt/5.15/gcc_64/bin:$PATH
      - sh: sudo apt update
      - sh: sudo apt install -y libgl1-mesa-dev
    build_script:
      - qmake OverlayPal.pro "CONFIG+=qtquickcompiler"
      - make
    after_build:
      - mkdir OverlayPal-dev-linux_x64-${CONFIGURATION}
      - cd OverlayPal-dev-linux_x64-${CONFIGURATION}
      - cp ../LICENSE ./
      - cp ../OverlayPal ./
      - cp -r ../nespalettes ./
      - cp ../src/cmpl/*.cmpl ./
      - appveyor DownloadFile http://www.coliop.org/_download/Cmpl-2-0-linux64.tar.gz
      - tar -xvf Cmpl-2-0-linux64.tar.gz
      - rm Cmpl-2-0-linux64.tar.gz
      - mv Cmpl-2-0-linux64 Cmpl
      - cd ..
      - tar -czvf OverlayPal-dev-linux_x64-${CONFIGURATION}.tar.gz OverlayPal-dev-linux_x64-${CONFIGURATION}
      - appveyor PushArtifact OverlayPal-dev-linux_x64-${CONFIGURATION}.tar.gz
